<?php
return [
    [
        "id" => "zh",
        "value" => "简体中文",
        "value_en_us" => "Chinese",
        "value_zh_tw" => "簡體中文",
        "value_ru_ru" => "Упрощенный китайский",
        "value_ar_ar" => "Cina Sederhana",
        "value_de_de" => "Vereinfachtes Chinesisch",
        "value_ja_jp" => "簡体字中国語",
        "value_ko_kr" => "중국어 간체",
        "value_ms_my" => "Cina Sederhana",
        "value_es_es" => "Chino simplificado",
        "value_th_th" => "ภาษาจีนตัวย่อ",
        "value_fr_fr" => "Chinois simplifié",
        "value_pt_pt" => "Chinês simplificado",
        "value_id_id" => "Cina Sederhana",
    ], [
        "id" => "cht",
        "value" => "繁体中文",
        "value_en_us" => "traditional Chinese",
        "value_zh_tw" => "繁體中文",
        "value_ru_ru" => "Китайский стиль",
        "value_ar_ar" => "Cina Tradisional",
        "value_de_de" => "Traditionelles Chinesisch",
        "value_ja_jp" => "繁体字中国語",
        "value_ko_kr" => "중국어 번체",
        "value_ms_my" => "Cina Tradisional",
        "value_es_es" => "Chino tradicional",
        "value_th_th" => "ภาษาจีนดั้งเดิม",
        "value_fr_fr" => "Chinois traditionnel",
        "value_pt_pt" => "Chinês tradicional",
        "value_id_id" => "Cina Tradisional",
    ], [
        "id" => "en",
        "value" => "英语",
        "value_en_us" => "English",
        "value_zh_tw" => "英語",
        "value_ru_ru" => "Английский язык",
        "value_ar_ar" => "Inggris",
        "value_de_de" => "Englisch",
        "value_ja_jp" => "英語",
        "value_ko_kr" => "영어",
        "value_ms_my" => "Inggeris",
        "value_es_es" => "Inglés",
        "value_th_th" => "ภาษาอังกฤษ",
        "value_fr_fr" => "Anglais",
        "value_pt_pt" => "Inglês",
        "value_id_id" => "Inggris",
    ], [
        "id" => "fra",
        "value" => "法语",
        "value_en_us" => "French",
        "value_zh_tw" => "法語",
        "value_ru_ru" => "Французский язык",
        "value_ar_ar" => "Perancis",
        "value_de_de" => "Französisch",
        "value_ja_jp" => "フランス語",
        "value_ko_kr" => "프랑스어",
        "value_ms_my" => "Perancis",
        "value_es_es" => "Francés",
        "value_th_th" => "ฝรั่งเศส",
        "value_fr_fr" => "Français",
        "value_pt_pt" => "Francês",
        "value_id_id" => "Perancis",
    ], [
        "id" => "ru",
        "value" => "俄语",
        "value_en_us" => "Russian",
        "value_zh_tw" => "俄語",
        "value_ru_ru" => "Русский язык",
        "value_ar_ar" => "Rusia",
        "value_de_de" => "Russisch",
        "value_ja_jp" => "ロシア語",
        "value_ko_kr" => "러시아어",
        "value_ms_my" => "RusiaName",
        "value_es_es" => "Ruso",
        "value_th_th" => "ภาษารัสเซีย",
        "value_fr_fr" => "Russe",
        "value_pt_pt" => "Russo",
        "value_id_id" => "Rusia",
    ], [
        "id" => "ara",
        "value" => "阿拉伯语",
        "value_en_us" => "Arabic",
        "value_zh_tw" => "阿拉伯語",
        "value_ru_ru" => "Арабский язык",
        "value_ar_ar" => "Arab",
        "value_de_de" => "Arabisch",
        "value_ja_jp" => "アラビア語",
        "value_ko_kr" => "아랍어",
        "value_ms_my" => "Arab",
        "value_es_es" => "árabe",
        "value_th_th" => "ภาษาอาหรับ",
        "value_fr_fr" => "Arabe",
        "value_pt_pt" => "Árabe",
        "value_id_id" => "Arab",
    ], [
        "id" => "pt",
        "value" => "葡萄牙语",
        "value_en_us" => "Portuguese",
        "value_zh_tw" => "葡萄牙語",
        "value_ru_ru" => "Португальский язык",
        "value_ar_ar" => "Portugis",
        "value_de_de" => "Portugiesisch",
        "value_ja_jp" => "ポルトガル語",
        "value_ko_kr" => "포르투갈어",
        "value_ms_my" => "Portugis",
        "value_es_es" => "Portugués",
        "value_th_th" => "โปรตุเกส",
        "value_fr_fr" => "Portugais",
        "value_pt_pt" => "Português",
        "value_id_id" => "Portugis",
    ], [
        "id" => "spa",
        "value" => "西班牙语",
        "value_en_us" => "Spanish",
        "value_zh_tw" => "西班牙語",
        "value_ru_ru" => "Испанский язык",
        "value_ar_ar" => "Spanyol",
        "value_de_de" => "Spanisch",
        "value_ja_jp" => "スペイン語",
        "value_ko_kr" => "스페인어",
        "value_ms_my" => "Sepanyol",
        "value_es_es" => "Español",
        "value_th_th" => "สเปน",
        "value_fr_fr" => "Espagnol",
        "value_pt_pt" => "Espanhol",
        "value_id_id" => "Spanyol",
    ], [
        "id" => "de",
        "value" => "德语",
        "value_en_us" => "German",
        "value_zh_tw" => "德語",
        "value_ru_ru" => "Немецкий язык",
        "value_ar_ar" => "Jerman",
        "value_de_de" => "Deutsch",
        "value_ja_jp" => "ドイツ語",
        "value_ko_kr" => "독일어",
        "value_ms_my" => "Jerman",
        "value_es_es" => "Alemán",
        "value_th_th" => "เยอรมัน",
        "value_fr_fr" => "Allemand",
        "value_pt_pt" => "Alemão",
        "value_id_id" => "Jerman",
    ], [
        "id" => "jp",
        "value" => "日语",
        "value_en_us" => "Japanese",
        "value_zh_tw" => "日語",
        "value_ru_ru" => "Японский язык",
        "value_ar_ar" => "Jepang",
        "value_de_de" => "Japanisch",
        "value_ja_jp" => "日本語",
        "value_ko_kr" => "일본어",
        "value_ms_my" => "Jepun",
        "value_es_es" => "Japonés",
        "value_th_th" => "ญี่ปุ่น",
        "value_fr_fr" => "Japonais",
        "value_pt_pt" => "Japonês",
        "value_id_id" => "Jepang",
    ], [
        "id" => "kor",
        "value" => "韩语",
        "value_en_us" => "Korean",
        "value_zh_tw" => "韓語",
        "value_ru_ru" => "Корейский язык",
        "value_ar_ar" => "Korea",
        "value_de_de" => "Koreanisch",
        "value_ja_jp" => "韓国語",
        "value_ko_kr" => "한국어",
        "value_ms_my" => "Korea",
        "value_es_es" => "Coreano",
        "value_th_th" => "เกาหลี",
        "value_fr_fr" => "Coréen",
        "value_pt_pt" => "Coreano",
        "value_id_id" => "Korea",
    ]/*, [
        "id" => "th",
        "value" => "泰语",
        "value_en_us" => "Thai"
    ], [
        "id" => "it",
        "value" => "意大利语",
        "value_en_us" => "Italian"
    ], [
        "id" => "el",
        "value" => "希腊语",
        "value_en_us" => "Greek"
    ], [
        "id" => "nl",
        "value" => "荷兰语",
        "value_en_us" => "Dutch"
    ], [
        "id" => "pl",
        "value" => "波兰语",
        "value_en_us" => "Polish"
    ], [
        "id" => "bul",
        "value" => "保加利亚语",
        "value_en_us" => "Bulgarian"
    ], [
        "id" => "est",
        "value" => "爱沙尼亚语",
        "value_en_us" => "Estonian"
    ], [
        "id" => "dan",
        "value" => "丹麦语",
        "value_en_us" => "Danish"
    ], [
        "id" => "fin",
        "value" => "芬兰语",
        "value_en_us" => "Finnish"
    ], [
        "id" => "cs",
        "value" => "捷克语",
        "value_en_us" => "Czech"
    ], [
        "id" => "rom",
        "value" => "罗马尼亚语",
        "value_en_us" => "Romanian"
    ], [
        "id" => "slo",
        "value" => "斯洛文尼亚语",
        "value_en_us" => "Slovene"
    ], [
        "id" => "swe",
        "value" => "瑞典语",
        "value_en_us" => "Swedish"
    ], [
        "id" => "hu",
        "value" => "匈牙利语",
        "value_en_us" => "Hungarian"
    ], [
        "id" => "vie",
        "value" => "越南语",
        "value_en_us" => "Vietnamese"
    ]*/
];